"""Verify the first hotel spine slice contains the intended product areas."""

from __future__ import annotations

import unreal


MAP_PATH = "/Game/Hotel/Maps/L_HotelNightShift_Slice"

REQUIRED_ASSETS = [
    MAP_PATH,
    "/Game/Hotel/Audio/SFX_PhoneRing_v0",
    "/Game/Hotel/Audio/SFX_PhonePickup_v0",
    "/Game/Hotel/Audio/SFX_PhoneLineStatic_v0",
    "/Game/Hotel/Audio/SFX_DoorKnock203_v0",
    "/Game/Hotel/Audio/SFX_Room203AftershockRustle_v0",
    "/Game/Hotel/Audio/SFX_ReportLogFiled_v0",
    "/Game/Hotel/Audio/SFX_PatrolListenDrop_v0",
    "/Game/Hotel/Audio/SFX_ReturnRouteKnockback_v0",
    "/Game/Hotel/Audio/SFX_PostReportMonitorMismatch_v0",
    "/Game/Hotel/Audio/SFX_PostReportDeskWaitRattle_v0",
    "/Game/Hotel/Audio/SFX_PostReportLogSelfCorrection_v0",
    "/Game/Hotel/Audio/AMB_LobbyFluorescentHum_v0",
    "/Game/Hotel/Audio/AMB_GuestHallDrone_v0",
    "/Game/Hotel/Audio/AMB_ElevatorShaftGroan_v0",
    "/Game/Hotel/Audio/AMB_StairwellAir_v0",
    "/Game/Hotel/Materials/M_Hotel_WornFloor_v0",
    "/Game/Hotel/Materials/M_Hotel_AgedWall_v0",
    "/Game/Hotel/Materials/M_Hotel_RoomDoorPaint_v0",
    "/Game/Hotel/Materials/M_Hotel_FluorescentPanelGlow_v0",
    "/Game/Hotel/Materials/M_Hotel_TarnishedBrass_v0",
    "/Game/Hotel/Materials/M_Hotel_DullDeskMetal_v0",
    "/Game/Hotel/Materials/M_Hotel_AgedLedgerRed_v0",
    "/Game/Hotel/Materials/M_Hotel_MonitorGreenGlow_v0",
    "/Game/Hotel/Materials/M_Hotel_AgedCallSlipPaper_v0",
    "/Game/Hotel/Materials/M_Hotel_PhoneBoneButton_v0",
    "/Game/Hotel/Materials/M_Hotel_WornRouteTape_v0",
    "/Game/Hotel/Materials/M_Hotel_PeeledWallpaperPaper_v0",
    "/Game/Hotel/Materials/M_Hotel_WallDampStain_v0",
    "/Game/Hotel/Materials/M_Hotel_PaperTearShadowBack_v0",
    "/Game/Hotel/Materials/M_Hotel_ExposedWallpaperBacking_v0",
    "/Game/Hotel/Materials/M_Hotel_TornPaperEdgeLight_v0",
    "/Game/Hotel/Materials/M_Hotel_FadedWallpaperStripe_v0",
    "/Game/Hotel/Materials/M_Hotel_Room203WallpaperPanel_v0",
    "/Game/Hotel/Materials/M_Hotel_FloorScuffDark_v0",
    "/Game/Hotel/Materials/M_Hotel_CeilingWaterStain_v0",
    "/Game/Hotel/Materials/M_Hotel_DoorPaintChipLight_v0",
    "/Game/Hotel/Meshes/SM_FrontDesk_OldPhoneBody_v0",
    "/Game/Hotel/Meshes/SM_FrontDesk_CurvedReceiver_v0",
    "/Game/Hotel/Meshes/SM_FrontDesk_CoiledPhoneCord_v0",
    "/Game/Hotel/Meshes/SM_FrontDesk_CurledLedgerPages_v0",
    "/Game/Hotel/Meshes/SM_Room203_PaneledDoor_v0",
    "/Game/Hotel/Meshes/SM_Room203_ChainLinks_v0",
    "/Game/Hotel/Meshes/SM_Room203_TornNotice_v0",
    "/Game/Hotel/Meshes/SM_Room203_HandleLever_v0",
    "/Game/Hotel/Meshes/SM_GuestHall_PeelingWallpaperPatch_v0",
    "/Game/Hotel/Meshes/SM_GuestHall_Room203AftershockPaper_v0",
    "/Game/Hotel/Meshes/SM_GuestHall_Room203AftershockTearShadow_v0",
    "/Game/Hotel/Meshes/SM_GuestHall_Room203AftershockRawEdge_v0",
    "/Game/Hotel/Meshes/SM_GuestHall_FloorScuffCluster_v0",
    "/Game/Hotel/Meshes/SM_GuestHall_CeilingWaterStain_v0",
    "/Game/Hotel/Textures/TX_Hotel_Room203WallpaperPanel_v0",
    "/Game/Hotel/Cinematics/LS_HotelSpine_Stills",
    "/Game/Hotel/Cinematics/MRQ_HotelEvidencePng",
]

REQUIRED_ACTOR_LABELS = [
    "PLAYERSTART_FrontDesk_FacingPhoneAndMonitor",
    "PROP_FrontDesk_Phone_AnswerLoopPlaceholder",
    "PROP_FrontDesk_DeskMat_UnderPhoneAndLog",
    "PROP_FrontDesk_Phone_BaseHeavyOldDeskSet",
    "PROP_FrontDesk_Phone_Keypad_ReadableCue",
    "PROP_FrontDesk_Phone_ButtonRowTop",
    "PROP_FrontDesk_Phone_ButtonRowBottom",
    "PROP_FrontDesk_Phone_CradleLeftHook",
    "PROP_FrontDesk_Phone_CradleRightHook",
    "PROP_FrontDesk_Phone_HookSwitch_DepressedCue",
    "PROP_FrontDesk_Phone_AuthoredCurvedBody",
    "PROP_FrontDesk_Phone_ReceiverCue",
    "PROP_FrontDesk_Phone_ReceiverLeftCap",
    "PROP_FrontDesk_Phone_ReceiverRightCap",
    "PROP_FrontDesk_Phone_ReceiverAuthoredSilhouette",
    "PROP_FrontDesk_Phone_CradleShadow",
    "PROP_FrontDesk_Phone_CoiledCordCue",
    "PROP_FrontDesk_Phone_CoiledCordLoopA",
    "PROP_FrontDesk_Phone_CoiledCordLoopB",
    "PROP_FrontDesk_Phone_CoiledCordLoopC",
    "PROP_FrontDesk_Phone_AuthoredCoiledCord",
    "PROP_FrontDesk_Phone_RoundedDialPlate",
    "PROP_FrontDesk_Phone_DialFingerHoleTop",
    "PROP_FrontDesk_Phone_DialFingerHoleLeft",
    "PROP_FrontDesk_Phone_DialFingerHoleRight",
    "PROP_FrontDesk_Phone_DialFingerStop",
    "PROP_FrontDesk_Phone_ReceiverLeftRoundCup",
    "PROP_FrontDesk_Phone_ReceiverRightRoundCup",
    "PROP_FrontDesk_Phone_CordRoundLoopA",
    "PROP_FrontDesk_Phone_CordRoundLoopB",
    "PROP_FrontDesk_Phone_CordRoundLoopC",
    "PROP_FrontDesk_ServiceBell_Dome",
    "PROP_FrontDesk_ServiceBell_Button",
    "PROP_FrontDesk_DeskLamp_RoundFoot",
    "PROP_FrontDesk_DeskLamp_ThinStem",
    "PROP_FrontDesk_DeskLamp_ShadeCurvedSilhouette",
    "LIGHTMESH_FrontDesk_PhoneCallLamp",
    "PROP_Surveillance_Monitor_PlayerChecksHall",
    "PROP_ReportLog_ReturnAndRecordPoint",
    "PROP_FrontDesk_NightLog_OpenPage_Readable",
    "PROP_FrontDesk_ReportLog_AuthoredCurledPages",
    "PROP_FrontDesk_ReportLog_ClipboardClip_Readable",
    "PROP_FrontDesk_ReportLog_IncidentHeaderCue",
    "PROP_FrontDesk_ReportLog_Room203EntryLine",
    "PROP_FrontDesk_ReportLog_TimeBoxCue",
    "PROP_FrontDesk_ReportLog_RefusedCheckbox",
    "PROP_FrontDesk_ReportLog_RefusedCheckmarkShort",
    "PROP_FrontDesk_ReportLog_RefusedCheckmarkLong",
    "PROP_FrontDesk_ReportLog_FiledStampCue",
    "PROP_FrontDesk_ReportLog_PenRest",
    "PROP_FrontDesk_ReportLog_PenTip",
    "PROP_FrontDesk_ReportLog_BinderRingTop",
    "PROP_FrontDesk_ReportLog_BinderRingBottom",
    "PROP_FrontDesk_ReportLog_RedInkSmear",
    "PROP_FrontDesk_ReportLog_SelfCorrectedRoom203OpenLine",
    "PROP_FrontDesk_ReportLog_SelfCorrectedNoGuestLine",
    "PROP_FrontDesk_ReportLog_SelfCorrectedTimestampSlash",
    "LIGHTMESH_FrontDesk_ReportLog_SelfCorrectionCue",
    "PROP_FrontDesk_CallSlip_Room203_CameraMismatchCue",
    "PROP_FrontDesk_CallSlip_Underline203",
    "PROP_FrontDesk_BackShelf_KeyHookA",
    "PROP_FrontDesk_BackShelf_KeyHookB",
    "PROP_FrontDesk_BackShelf_KeyHookC",
    "PROP_FrontDesk_BackShelf_KeyTag203",
    "PROP_Surveillance_Monitor_PostReportFeedFrame",
    "PROP_Surveillance_Monitor_PostReportStaticBarA",
    "PROP_Surveillance_Monitor_PostReportStaticBarB",
    "PROP_Surveillance_Monitor_PostReportOpenDoorGlyph",
    "PROP_Surveillance_Monitor_PostReportRoom203Dot",
    "PROP_Surveillance_Monitor_PostReportTimestampSmear",
    "PROP_FrontDesk_FloorWaitMarker_PostReport",
    "PROP_FrontDesk_CounterHoldLine_PostReport",
    "PROP_Lobby_GlassDoor_PostReportHoldClosedTape",
    "PROP_Lobby_GlassDoor_PostReportOutsidePalmSmear",
    "PROP_Lobby_GlassDoor_PostReportNoGuestReflection",
    "LIGHTMESH_LobbyDoor_PostReportRattleCue",
    "PROP_Lobby_GlassDoor_PostReportHandleRattleBar",
    "PROP_Lobby_GlassDoor_PostReportLatchRattlePin",
    "PROP_Lobby_GlassDoor_PostReportTapeLooseEnd",
    "AREA_FrontDesk_Ceiling_LowPressure",
    "AREA_Transition_CarpetRun_ToGuestHall_NoVoid",
    "AREA_Transition_LeftSightlineWall_ToGuestHall",
    "AREA_Transition_RightSightlineWall_ToGuestHall",
    "TRANSITION_Elevator_Door_AudibleBeforeSeen",
    "TRANSITION_Elevator_CallPanel_SoundCueAnchor",
    "TRANSITION_Elevator_FloorIndicator_WrongFloorCue",
    "TRANSITION_Elevator_ClosedSeam_ShadowCue",
    "TRANSITION_EmergencyStair_Door_AlternateRoute",
    "TRANSITION_EmergencyStair_ExitSign_ColdCue",
    "TRANSITION_EmergencyStair_DoorHandle_ShadowCue",
    "TRANSITION_ServiceBackHall_LockedShortcut",
    "TRANSITION_ServiceBackHall_ChainLockedShortcutCue",
    "PATROL_Route_DecisionStopLine_ListenBeforeMoving",
    "PATROL_Route_DecisionStopLine_CenterBreak",
    "PATROL_Route_ElevatorTrack_FootstepA",
    "PATROL_Route_ElevatorTrack_FootstepB",
    "PATROL_Route_ElevatorTrack_FootstepStopped",
    "PATROL_Route_StairReturn_FootstepA",
    "PATROL_Route_StairReturn_FootstepB",
    "PATROL_Route_StairReturn_ScrapeMark",
    "PATROL_Route_DroppedKeyTag_ReturnCue",
    "PATROL_Route_NightAuditClipboard_ElevatorOrStairChoice",
    "PATROL_Route_Clipboard_ElevatorMark",
    "PATROL_Route_Clipboard_StairMark",
    "PATROL_Route_WallArrow_ElevatorNoiseCue",
    "PATROL_Route_WallArrow_StairAirCue",
    "PATROL_Route_StairDoor_ColdLightLeak",
    "AREA_GuestHall_Floor_OneDoorSlice",
    "PROP_GuestHall_RightWall_Baseboard_RunTo203_A",
    "PROP_GuestHall_RightWall_Baseboard_RunTo203_B",
    "PROP_GuestHall_LeftWall_Baseboard_CameraSide",
    "PROP_GuestHall_Room203_FramePaintChip_LeftTop",
    "PROP_GuestHall_Room203_FramePaintChip_LeftLow",
    "PROP_GuestHall_Room203_FramePaintChip_RightMid",
    "PROP_GuestHall_Room203_ThresholdDustCollect",
    "PROP_GuestHall_LeftWall_DampPatch_CameraSide",
    "PROP_GuestHall_RightWall_FadedWallpaperStripe_Room203_A",
    "PROP_GuestHall_RightWall_FadedWallpaperStripe_Room203_B",
    "PROP_GuestHall_RightWall_FadedWallpaperStripe_Room203_C",
    "PROP_GuestHall_RightWall_FadedWallpaperStripe_Room203_D",
    "PROP_GuestHall_RightWall_FadedWallpaperWaterline_Room203",
    "PROP_GuestHall_RightWall_AuthoredDampUnderPeel_Room203Approach",
    "PROP_GuestHall_RightWall_AuthoredPeelingWallpaper_CameraReadable",
    "PROP_GuestHall_RightWall_AuthoredPeelingWallpaper_Room203",
    "PROP_GuestHall_RightWall_Room203AftershockTearShadow",
    "PROP_GuestHall_RightWall_Room203AftershockLoosePaper",
    "PROP_GuestHall_RightWall_Room203AftershockHighCurl",
    "PROP_GuestHall_RightWall_Room203AftershockLowCurl",
    "PROP_GuestHall_RightWall_Room203AftershockRawEdgeThreads",
    "PROP_GuestHall_Floor_AuthoredScuffPath_ToRoom203",
    "PROP_GuestHall_Ceiling_AuthoredWaterStain_FluorescentB",
    "RETURN_Route_FloorColdPatch_AfterRefusal",
    "RETURN_Route_BackKnockDirectionStripe",
    "RETURN_Route_BackKnockDirectionStripe_Return",
    "RETURN_Route_WallStatusSlip_ReportAfterHall",
    "RETURN_Route_WallStatusSlip_Underline",
    "RETURN_Route_FootprintBacktrackA",
    "RETURN_Route_FootprintBacktrackB",
    "RETURN_Route_FootprintBacktrackC",
    "RETURN_Route_CeilingLightmesh_ColdPulseCue",
    "PROP_GuestHall_RoomDoor203_OpenRefuseDecision",
    "PROP_GuestHall_Room203_AuthoredPaneledDoor",
    "PROP_GuestHall_Room203_LeftDoorJamb",
    "PROP_GuestHall_Room203_RightDoorJamb",
    "PROP_GuestHall_Room203_TopDoorJamb",
    "PROP_GuestHall_Room203_DarkLatchGap",
    "PROP_GuestHall_Room203_HandleBackplate_Readable",
    "PROP_GuestHall_Room203_AuthoredHandleLever",
    "PROP_GuestHall_Room203_LatchJoltCue",
    "PROP_GuestHall_Room203_ChainJoltCue",
    "PROP_GuestHall_Room203_AuthoredChainLinks",
    "PROP_GuestHall_Room203_DoorEdgeSlamShadowCue",
    "PROP_GuestHall_Room203_NoticeCornerJoltCue",
    "PROP_GuestHall_Room203_AuthoredTornNotice",
    "PROP_GuestHall_Room203_PeepholeBlackCue",
    "PROP_GuestHall_Room203_DoNotOpenNotice",
    "PROP_GuestHall_Room203_NoticeUnderline",
    "PROP_GuestHall_Room203_ThresholdShadow",
    "SFX_PhoneRing_FrontDesk_ManualTrigger_v0",
    "SFX_PhonePickup_FrontDesk_ManualTrigger_v0",
    "SFX_PhoneLineStatic_FrontDesk_ConnectedCue_v0",
    "SFX_DoorKnock203_ManualTrigger_v0",
    "SFX_Room203AftershockRustle_ManualTrigger_v0",
    "SFX_ReportLogFiled_FrontDesk_ManualTrigger_v0",
    "AMB_Lobby_FluorescentHum_Source_v0",
    "AMB_GuestHall_Drone_Source_v0",
    "AMB_Elevator_ShaftGroan_Source_v0",
    "AMB_Stairwell_Air_Source_v0",
    "AMB_PatrolRoute_ElevatorGroanBleed_Source_v0",
    "AMB_PatrolRoute_StairAirBleed_Source_v0",
    "SFX_PatrolListen_StopLine_ManualTrigger_v0",
    "SFX_ReturnRoute_BackKnock_ManualTrigger_v0",
    "SFX_PostReportMonitorMismatch_ManualTrigger_v0",
    "SFX_PostReportDeskWait_Rattle_ManualTrigger_v0",
    "SFX_PostReportLogSelfCorrection_ManualTrigger_v0",
    "CAPTURE_FrontDesk_FirstSteamShotCandidate",
    "CAPTURE_ReportLog_ReadabilityCandidate",
    "CAPTURE_PhoneResponse_LiftReceiverCandidate",
    "CAPTURE_Transition_ElevatorStair_AudioFearCandidate",
    "CAPTURE_PatrolRoute_DecisionCueCandidate",
    "CAPTURE_GuestDoor_15SecondBeatCandidate",
    "CAPTURE_ReturnRoute_BackKnockCandidate",
    "CAPTURE_PostReportMonitorMismatchCandidate",
    "CAPTURE_PostReportDeskWait_DoNotAnswerCandidate",
    "CAPTURE_PostReportLogSelfCorrectionCandidate",
    "LIGHTMESH_FrontDesk_OverheadFluorescent",
    "LIGHTMESH_GuestHall_FluorescentPanelA",
    "LIGHTMESH_GuestHall_FluorescentPanelB",
    "LIGHT_FrontDesk_WorkSurfacePracticalFill",
    "LIGHT_FrontDesk_PhoneCallLampPulse",
    "LIGHT_FrontDesk_CaptureEvidenceSoftFill",
    "LIGHT_Transition_ElevatorCallPanelDread",
    "LIGHT_Transition_StairExitCold",
    "LIGHT_Transition_CaptureEvidenceSoftFill",
    "LIGHT_PatrolRoute_DecisionCueFloorFill",
    "LIGHT_ReturnRoute_ColdPulseAfterRefusal",
    "LIGHT_GuestHall_Room203PlatePractical",
    "LIGHT_GuestHall_CaptureEvidenceDoorFill",
    "LIGHT_GuestHall_Room203AftershockPaperSkimFill",
    "LIGHT_MonitorToHall_CaptureEvidenceGreenFill",
    "LIGHT_LobbyDoor_PostReportRattleColdPulse",
    "LIGHT_FrontDesk_ReportLog_SelfCorrectionAmberPulse",
    "PPV_HotelNightShift_ReadableHorrorExposure",
]

ROOM203_SURFACE_PASS_TAGS = [
    "Hotel.Capture.Readability",
    "Hotel.Capture.GuestDoor",
    "Hotel.Capture.Room203Surface",
    "Hotel.ArtDensity.GuestHall",
    "Hotel.ArtDensity.Room203",
    "Hotel.ArtSurface.Room203MaterialPass",
    "Hotel.ArtSource.ProjectAuthoredMaterial",
]

ROOM203_SURFACE_PASS_AUTHORED_MESH_TAGS = ROOM203_SURFACE_PASS_TAGS + ["Hotel.ArtSource.AuthoredMesh"]

ROOM203_WALLPAPER_FLUTTER_TAGS = ROOM203_SURFACE_PASS_AUTHORED_MESH_TAGS + [
    "Hotel.Feedback.Room203WallpaperFlutter",
    "Hotel.Capture.Room203Aftershock",
]


REQUIRED_ACTOR_TAGS = {
    "PROP_FrontDesk_Phone_AnswerLoopPlaceholder": ["Hotel.Interact.Phone"],
    "PROP_FrontDesk_DeskMat_UnderPhoneAndLog": ["Hotel.Capture.Readability", "Hotel.Feedback.PhoneResponseVisual"],
    "PROP_FrontDesk_Phone_Keypad_ReadableCue": ["Hotel.Capture.Readability", "Hotel.Feedback.PhoneResponseVisual"],
    "PROP_FrontDesk_Phone_ButtonRowTop": ["Hotel.Capture.Readability", "Hotel.Feedback.PhoneResponseVisual"],
    "PROP_FrontDesk_Phone_ButtonRowBottom": ["Hotel.Capture.Readability", "Hotel.Feedback.PhoneResponseVisual"],
    "PROP_FrontDesk_Phone_CradleLeftHook": ["Hotel.Capture.Readability", "Hotel.Feedback.PhoneResponseVisual"],
    "PROP_FrontDesk_Phone_CradleRightHook": ["Hotel.Capture.Readability", "Hotel.Feedback.PhoneResponseVisual"],
    "PROP_FrontDesk_Phone_HookSwitch_DepressedCue": ["Hotel.Capture.Readability", "Hotel.Feedback.PhoneResponseVisual"],
    "PROP_FrontDesk_Phone_AuthoredCurvedBody": ["Hotel.Capture.Readability", "Hotel.ArtDensity.FrontDesk", "Hotel.ArtSource.AuthoredMesh"],
    "PROP_FrontDesk_Phone_ReceiverCue": ["Hotel.Feedback.PhoneReceiver", "Hotel.Capture.Readability"],
    "PROP_FrontDesk_Phone_ReceiverLeftCap": ["Hotel.Feedback.PhoneReceiver", "Hotel.Capture.Readability"],
    "PROP_FrontDesk_Phone_ReceiverRightCap": ["Hotel.Feedback.PhoneReceiver", "Hotel.Capture.Readability"],
    "PROP_FrontDesk_Phone_ReceiverAuthoredSilhouette": ["Hotel.Feedback.PhoneReceiver", "Hotel.Capture.Readability", "Hotel.ArtDensity.FrontDesk", "Hotel.ArtSource.AuthoredMesh"],
    "PROP_FrontDesk_Phone_CoiledCordLoopA": ["Hotel.Capture.Readability", "Hotel.Feedback.PhoneResponseVisual"],
    "PROP_FrontDesk_Phone_CoiledCordLoopB": ["Hotel.Capture.Readability", "Hotel.Feedback.PhoneResponseVisual"],
    "PROP_FrontDesk_Phone_CoiledCordLoopC": ["Hotel.Capture.Readability", "Hotel.Feedback.PhoneResponseVisual"],
    "PROP_FrontDesk_Phone_AuthoredCoiledCord": ["Hotel.Capture.Readability", "Hotel.ArtDensity.FrontDesk", "Hotel.ArtSource.AuthoredMesh", "Hotel.Feedback.PhoneCordTug"],
    "PROP_FrontDesk_Phone_RoundedDialPlate": ["Hotel.Capture.Readability", "Hotel.ArtDensity.FrontDesk"],
    "PROP_FrontDesk_Phone_DialFingerHoleTop": ["Hotel.Capture.Readability", "Hotel.ArtDensity.FrontDesk"],
    "PROP_FrontDesk_Phone_DialFingerHoleLeft": ["Hotel.Capture.Readability", "Hotel.ArtDensity.FrontDesk"],
    "PROP_FrontDesk_Phone_DialFingerHoleRight": ["Hotel.Capture.Readability", "Hotel.ArtDensity.FrontDesk"],
    "PROP_FrontDesk_Phone_DialFingerStop": ["Hotel.Capture.Readability", "Hotel.ArtDensity.FrontDesk"],
    "PROP_FrontDesk_Phone_ReceiverLeftRoundCup": ["Hotel.Feedback.PhoneReceiver", "Hotel.Capture.Readability", "Hotel.ArtDensity.FrontDesk"],
    "PROP_FrontDesk_Phone_ReceiverRightRoundCup": ["Hotel.Feedback.PhoneReceiver", "Hotel.Capture.Readability", "Hotel.ArtDensity.FrontDesk"],
    "PROP_FrontDesk_Phone_CordRoundLoopA": ["Hotel.Capture.Readability", "Hotel.ArtDensity.FrontDesk"],
    "PROP_FrontDesk_Phone_CordRoundLoopB": ["Hotel.Capture.Readability", "Hotel.ArtDensity.FrontDesk"],
    "PROP_FrontDesk_Phone_CordRoundLoopC": ["Hotel.Capture.Readability", "Hotel.ArtDensity.FrontDesk"],
    "PROP_FrontDesk_ServiceBell_Dome": ["Hotel.Capture.Readability", "Hotel.ArtDensity.FrontDesk"],
    "PROP_FrontDesk_ServiceBell_Button": ["Hotel.Capture.Readability", "Hotel.ArtDensity.FrontDesk"],
    "PROP_FrontDesk_DeskLamp_RoundFoot": ["Hotel.Capture.Readability", "Hotel.ArtDensity.FrontDesk"],
    "PROP_FrontDesk_DeskLamp_ThinStem": ["Hotel.Capture.Readability", "Hotel.ArtDensity.FrontDesk"],
    "PROP_FrontDesk_DeskLamp_ShadeCurvedSilhouette": ["Hotel.Capture.Readability", "Hotel.ArtDensity.FrontDesk"],
    "PROP_FrontDesk_CallSlip_Room203_CameraMismatchCue": ["Hotel.Capture.Readability", "Hotel.Feedback.PhoneResponseVisual"],
    "PROP_FrontDesk_CallSlip_Underline203": ["Hotel.Capture.Readability", "Hotel.Feedback.PhoneResponseVisual"],
    "PROP_Surveillance_Monitor_PostReportFeedFrame": ["Hotel.Capture.Readability", "Hotel.Capture.PostReportMonitorMismatch", "Hotel.Feedback.PostReportMonitorMismatchVisual"],
    "PROP_Surveillance_Monitor_PostReportStaticBarA": ["Hotel.Capture.Readability", "Hotel.Capture.PostReportMonitorMismatch", "Hotel.Feedback.PostReportMonitorMismatchVisual"],
    "PROP_Surveillance_Monitor_PostReportStaticBarB": ["Hotel.Capture.Readability", "Hotel.Capture.PostReportMonitorMismatch", "Hotel.Feedback.PostReportMonitorMismatchVisual"],
    "PROP_Surveillance_Monitor_PostReportOpenDoorGlyph": ["Hotel.Capture.Readability", "Hotel.Capture.PostReportMonitorMismatch", "Hotel.Feedback.PostReportMonitorMismatchVisual"],
    "PROP_Surveillance_Monitor_PostReportRoom203Dot": ["Hotel.Capture.Readability", "Hotel.Capture.PostReportMonitorMismatch", "Hotel.Feedback.PostReportMonitorMismatchVisual"],
    "PROP_Surveillance_Monitor_PostReportTimestampSmear": ["Hotel.Capture.Readability", "Hotel.Capture.PostReportMonitorMismatch", "Hotel.Feedback.PostReportMonitorMismatchVisual"],
    "PROP_FrontDesk_FloorWaitMarker_PostReport": ["Hotel.Capture.Readability", "Hotel.Capture.PostReportDeskWait", "Hotel.Feedback.PostReportDeskWaitVisual"],
    "PROP_FrontDesk_CounterHoldLine_PostReport": ["Hotel.Capture.Readability", "Hotel.Capture.PostReportDeskWait", "Hotel.Feedback.PostReportDeskWaitVisual"],
    "PROP_Lobby_GlassDoor_PostReportHoldClosedTape": ["Hotel.Capture.Readability", "Hotel.Capture.PostReportDeskWait", "Hotel.Feedback.PostReportDeskWaitVisual"],
    "PROP_Lobby_GlassDoor_PostReportOutsidePalmSmear": ["Hotel.Capture.Readability", "Hotel.Capture.PostReportDeskWait", "Hotel.Feedback.PostReportDeskWaitVisual"],
    "PROP_Lobby_GlassDoor_PostReportNoGuestReflection": ["Hotel.Capture.Readability", "Hotel.Capture.PostReportDeskWait", "Hotel.Feedback.PostReportDeskWaitVisual"],
    "LIGHTMESH_LobbyDoor_PostReportRattleCue": ["Hotel.Capture.Readability", "Hotel.Capture.PostReportDeskWait", "Hotel.Feedback.PostReportDeskWaitVisual"],
    "LIGHTMESH_FrontDesk_PhoneCallLamp": ["Hotel.Feedback.PhoneRingLamp", "Hotel.Capture.Readability"],
    "PROP_Surveillance_Monitor_PlayerChecksHall": ["Hotel.Interact.Monitor"],
    "PROP_GuestHall_RoomDoor203_OpenRefuseDecision": ["Hotel.Interact.Room203Door"],
    "PROP_GuestHall_RightWall_Baseboard_RunTo203_A": ROOM203_SURFACE_PASS_TAGS,
    "PROP_GuestHall_RightWall_Baseboard_RunTo203_B": ROOM203_SURFACE_PASS_TAGS,
    "PROP_GuestHall_LeftWall_Baseboard_CameraSide": ROOM203_SURFACE_PASS_TAGS,
    "PROP_GuestHall_Room203_FramePaintChip_LeftTop": ROOM203_SURFACE_PASS_TAGS,
    "PROP_GuestHall_Room203_FramePaintChip_LeftLow": ROOM203_SURFACE_PASS_TAGS,
    "PROP_GuestHall_Room203_FramePaintChip_RightMid": ROOM203_SURFACE_PASS_TAGS,
    "PROP_GuestHall_Room203_ThresholdDustCollect": ROOM203_SURFACE_PASS_TAGS,
    "PROP_GuestHall_LeftWall_DampPatch_CameraSide": ROOM203_SURFACE_PASS_TAGS,
    "PROP_GuestHall_RightWall_FadedWallpaperStripe_Room203_A": ROOM203_SURFACE_PASS_TAGS + ["Hotel.Capture.Room203Aftershock"],
    "PROP_GuestHall_RightWall_FadedWallpaperStripe_Room203_B": ROOM203_SURFACE_PASS_TAGS + ["Hotel.Capture.Room203Aftershock"],
    "PROP_GuestHall_RightWall_FadedWallpaperStripe_Room203_C": ROOM203_SURFACE_PASS_TAGS + ["Hotel.Capture.Room203Aftershock"],
    "PROP_GuestHall_RightWall_FadedWallpaperStripe_Room203_D": ROOM203_SURFACE_PASS_TAGS + ["Hotel.Capture.Room203Aftershock"],
    "PROP_GuestHall_RightWall_FadedWallpaperWaterline_Room203": ROOM203_SURFACE_PASS_TAGS + ["Hotel.Capture.Room203Aftershock"],
    "PROP_GuestHall_RightWall_AuthoredDampUnderPeel_Room203Approach": ROOM203_SURFACE_PASS_AUTHORED_MESH_TAGS,
    "PROP_GuestHall_RightWall_AuthoredPeelingWallpaper_CameraReadable": ROOM203_WALLPAPER_FLUTTER_TAGS,
    "PROP_GuestHall_RightWall_AuthoredPeelingWallpaper_Room203": ROOM203_WALLPAPER_FLUTTER_TAGS,
    "PROP_GuestHall_RightWall_Room203AftershockTearShadow": ROOM203_SURFACE_PASS_AUTHORED_MESH_TAGS + ["Hotel.Capture.Room203Aftershock"],
    "PROP_GuestHall_RightWall_Room203AftershockLoosePaper": ROOM203_WALLPAPER_FLUTTER_TAGS,
    "PROP_GuestHall_RightWall_Room203AftershockHighCurl": ROOM203_WALLPAPER_FLUTTER_TAGS,
    "PROP_GuestHall_RightWall_Room203AftershockLowCurl": ROOM203_WALLPAPER_FLUTTER_TAGS,
    "PROP_GuestHall_RightWall_Room203AftershockRawEdgeThreads": ROOM203_SURFACE_PASS_AUTHORED_MESH_TAGS + ["Hotel.Capture.Room203Aftershock"],
    "PROP_GuestHall_Floor_AuthoredScuffPath_ToRoom203": ROOM203_SURFACE_PASS_AUTHORED_MESH_TAGS,
    "PROP_GuestHall_Ceiling_AuthoredWaterStain_FluorescentB": ROOM203_SURFACE_PASS_AUTHORED_MESH_TAGS,
    "PROP_GuestHall_Room203_AuthoredPaneledDoor": ["Hotel.Capture.Readability", "Hotel.ArtDensity.Room203", "Hotel.ArtSource.AuthoredMesh", "Hotel.Feedback.Room203Refusal", "Hotel.Feedback.Room203DoorSurfaceJolt"],
    "PROP_GuestHall_Room203_HandleBackplate_Readable": ["Hotel.Capture.Readability", "Hotel.Feedback.Room203DoorDecisionVisual"],
    "PROP_GuestHall_Room203_AuthoredHandleLever": ["Hotel.Capture.Readability", "Hotel.ArtDensity.Room203", "Hotel.ArtSource.AuthoredMesh", "Hotel.Feedback.Room203Refusal", "Hotel.Feedback.Room203LatchJolt"],
    "PROP_GuestHall_Room203_LatchJoltCue": ["Hotel.Feedback.Room203Refusal", "Hotel.Capture.Readability", "Hotel.Feedback.Room203LatchJolt"],
    "PROP_GuestHall_Room203_ChainJoltCue": ["Hotel.Feedback.Room203Refusal", "Hotel.Capture.Readability", "Hotel.Feedback.Room203ChainJolt"],
    "PROP_GuestHall_Room203_AuthoredChainLinks": ["Hotel.Capture.Readability", "Hotel.ArtDensity.Room203", "Hotel.ArtSource.AuthoredMesh", "Hotel.Feedback.Room203Refusal", "Hotel.Feedback.Room203ChainJolt"],
    "PROP_GuestHall_Room203_DoorEdgeSlamShadowCue": ["Hotel.Feedback.Room203Refusal", "Hotel.Capture.Readability", "Hotel.Feedback.Room203DoorSurfaceJolt"],
    "PROP_GuestHall_Room203_NoticeCornerJoltCue": ["Hotel.Feedback.Room203Refusal", "Hotel.Capture.Readability", "Hotel.Feedback.Room203DoorSurfaceJolt"],
    "PROP_GuestHall_Room203_AuthoredTornNotice": ["Hotel.Capture.Readability", "Hotel.ArtDensity.Room203", "Hotel.ArtSource.AuthoredMesh", "Hotel.Feedback.Room203Refusal", "Hotel.Feedback.Room203DoorSurfaceJolt"],
    "PROP_GuestHall_Room203_PeepholeBlackCue": ["Hotel.Capture.Readability", "Hotel.Feedback.Room203DoorDecisionVisual"],
    "PROP_GuestHall_Room203_DoNotOpenNotice": ["Hotel.Capture.Readability", "Hotel.Feedback.Room203DoorDecisionVisual"],
    "PROP_GuestHall_Room203_NoticeUnderline": ["Hotel.Capture.Readability", "Hotel.Feedback.Room203DoorDecisionVisual"],
    "PROP_GuestHall_Room203_ThresholdShadow": ["Hotel.Capture.Readability", "Hotel.Feedback.Room203DoorDecisionVisual"],
    "PROP_ReportLog_ReturnAndRecordPoint": ["Hotel.Interact.ReportLog"],
    "PROP_FrontDesk_ReportLog_AuthoredCurledPages": ["Hotel.Capture.Readability", "Hotel.ArtDensity.FrontDesk", "Hotel.ArtSource.AuthoredMesh"],
    "PROP_FrontDesk_ReportLog_ClipboardClip_Readable": ["Hotel.Capture.Readability", "Hotel.Feedback.ReportLogVisual"],
    "PROP_FrontDesk_ReportLog_IncidentHeaderCue": ["Hotel.Capture.Readability", "Hotel.Feedback.ReportLogVisual"],
    "PROP_FrontDesk_ReportLog_Room203EntryLine": ["Hotel.Capture.Readability", "Hotel.Feedback.ReportLogVisual"],
    "PROP_FrontDesk_ReportLog_TimeBoxCue": ["Hotel.Capture.Readability", "Hotel.Feedback.ReportLogVisual"],
    "PROP_FrontDesk_ReportLog_RefusedCheckbox": ["Hotel.Capture.Readability", "Hotel.Feedback.ReportLogVisual"],
    "PROP_FrontDesk_ReportLog_RefusedCheckmarkShort": ["Hotel.Capture.Readability", "Hotel.Feedback.ReportLogVisual"],
    "PROP_FrontDesk_ReportLog_RefusedCheckmarkLong": ["Hotel.Capture.Readability", "Hotel.Feedback.ReportLogVisual"],
    "PROP_FrontDesk_ReportLog_FiledStampCue": ["Hotel.Capture.Readability", "Hotel.Feedback.ReportLogVisual", "Hotel.Feedback.ReportLogFiled"],
    "PROP_FrontDesk_ReportLog_PenRest": ["Hotel.Capture.Readability", "Hotel.Feedback.ReportLogVisual"],
    "PROP_FrontDesk_ReportLog_PenTip": ["Hotel.Capture.Readability", "Hotel.Feedback.ReportLogVisual"],
    "PROP_FrontDesk_ReportLog_BinderRingTop": ["Hotel.Capture.Readability", "Hotel.ArtDensity.FrontDesk"],
    "PROP_FrontDesk_ReportLog_BinderRingBottom": ["Hotel.Capture.Readability", "Hotel.ArtDensity.FrontDesk"],
    "PROP_FrontDesk_ReportLog_RedInkSmear": ["Hotel.Capture.Readability", "Hotel.ArtDensity.FrontDesk"],
    "PROP_FrontDesk_ReportLog_SelfCorrectedRoom203OpenLine": ["Hotel.Capture.Readability", "Hotel.Capture.PostReportLogSelfCorrection", "Hotel.Feedback.PostReportLogSelfCorrection"],
    "PROP_FrontDesk_ReportLog_SelfCorrectedNoGuestLine": ["Hotel.Capture.Readability", "Hotel.Capture.PostReportLogSelfCorrection", "Hotel.Feedback.PostReportLogSelfCorrection"],
    "PROP_FrontDesk_ReportLog_SelfCorrectedTimestampSlash": ["Hotel.Capture.Readability", "Hotel.Capture.PostReportLogSelfCorrection", "Hotel.Feedback.PostReportLogSelfCorrection"],
    "LIGHTMESH_FrontDesk_ReportLog_SelfCorrectionCue": ["Hotel.Capture.Readability", "Hotel.Capture.PostReportLogSelfCorrection", "Hotel.Feedback.PostReportLogSelfCorrectionVisual"],
    "LIGHT_FrontDesk_PhoneResponseEvidenceFill": ["Hotel.Capture.Readability", "Hotel.Capture.PhoneResponse"],
    "PROP_FrontDesk_BackShelf_KeyHookA": ["Hotel.Capture.Readability", "Hotel.ArtDensity.FrontDesk"],
    "PROP_FrontDesk_BackShelf_KeyHookB": ["Hotel.Capture.Readability", "Hotel.ArtDensity.FrontDesk"],
    "PROP_FrontDesk_BackShelf_KeyHookC": ["Hotel.Capture.Readability", "Hotel.ArtDensity.FrontDesk"],
    "PROP_FrontDesk_BackShelf_KeyTag203": ["Hotel.Capture.Readability", "Hotel.ArtDensity.FrontDesk"],
    "PROP_Lobby_GlassDoor_PostReportHandleRattleBar": ["Hotel.Capture.Readability", "Hotel.Capture.PostReportDeskWait", "Hotel.Feedback.PostReportDeskWaitRattle", "Hotel.ArtDensity.FrontDesk"],
    "PROP_Lobby_GlassDoor_PostReportLatchRattlePin": ["Hotel.Capture.Readability", "Hotel.Capture.PostReportDeskWait", "Hotel.Feedback.PostReportDeskWaitRattle", "Hotel.ArtDensity.FrontDesk"],
    "PROP_Lobby_GlassDoor_PostReportTapeLooseEnd": ["Hotel.Capture.Readability", "Hotel.Capture.PostReportDeskWait", "Hotel.Feedback.PostReportDeskWaitRattle", "Hotel.ArtDensity.FrontDesk"],
    "TRANSITION_Elevator_Door_AudibleBeforeSeen": ["Hotel.Capture.Readability", "Hotel.Capture.TransitionFear"],
    "TRANSITION_Elevator_CallPanel_SoundCueAnchor": ["Hotel.Capture.Readability", "Hotel.Capture.TransitionFear"],
    "TRANSITION_Elevator_FloorIndicator_WrongFloorCue": ["Hotel.Capture.Readability", "Hotel.Capture.TransitionFear"],
    "TRANSITION_Elevator_ClosedSeam_ShadowCue": ["Hotel.Capture.Readability", "Hotel.Capture.TransitionFear"],
    "TRANSITION_EmergencyStair_Door_AlternateRoute": ["Hotel.Capture.Readability", "Hotel.Capture.TransitionFear"],
    "TRANSITION_EmergencyStair_ExitSign_ColdCue": ["Hotel.Capture.Readability", "Hotel.Capture.TransitionFear"],
    "TRANSITION_EmergencyStair_DoorHandle_ShadowCue": ["Hotel.Capture.Readability", "Hotel.Capture.TransitionFear"],
    "TRANSITION_ServiceBackHall_LockedShortcut": ["Hotel.Capture.Readability", "Hotel.Capture.TransitionFear"],
    "TRANSITION_ServiceBackHall_ChainLockedShortcutCue": ["Hotel.Capture.Readability", "Hotel.Capture.TransitionFear"],
    "PATROL_Route_DecisionStopLine_ListenBeforeMoving": ["Hotel.Capture.Readability", "Hotel.Capture.TransitionFear", "Hotel.Capture.PatrolDecision"],
    "PATROL_Route_DecisionStopLine_CenterBreak": ["Hotel.Capture.Readability", "Hotel.Capture.TransitionFear", "Hotel.Capture.PatrolDecision"],
    "PATROL_Route_ElevatorTrack_FootstepA": ["Hotel.Capture.Readability", "Hotel.Capture.TransitionFear", "Hotel.Capture.PatrolDecision"],
    "PATROL_Route_ElevatorTrack_FootstepB": ["Hotel.Capture.Readability", "Hotel.Capture.TransitionFear", "Hotel.Capture.PatrolDecision"],
    "PATROL_Route_ElevatorTrack_FootstepStopped": ["Hotel.Capture.Readability", "Hotel.Capture.TransitionFear", "Hotel.Capture.PatrolDecision"],
    "PATROL_Route_StairReturn_FootstepA": ["Hotel.Capture.Readability", "Hotel.Capture.TransitionFear", "Hotel.Capture.PatrolDecision"],
    "PATROL_Route_StairReturn_FootstepB": ["Hotel.Capture.Readability", "Hotel.Capture.TransitionFear", "Hotel.Capture.PatrolDecision"],
    "PATROL_Route_StairReturn_ScrapeMark": ["Hotel.Capture.Readability", "Hotel.Capture.TransitionFear", "Hotel.Capture.PatrolDecision"],
    "PATROL_Route_DroppedKeyTag_ReturnCue": ["Hotel.Capture.Readability", "Hotel.Capture.TransitionFear", "Hotel.Capture.PatrolDecision"],
    "PATROL_Route_NightAuditClipboard_ElevatorOrStairChoice": ["Hotel.Capture.Readability", "Hotel.Capture.TransitionFear", "Hotel.Capture.PatrolDecision"],
    "PATROL_Route_Clipboard_ElevatorMark": ["Hotel.Capture.Readability", "Hotel.Capture.TransitionFear", "Hotel.Capture.PatrolDecision"],
    "PATROL_Route_Clipboard_StairMark": ["Hotel.Capture.Readability", "Hotel.Capture.TransitionFear", "Hotel.Capture.PatrolDecision"],
    "PATROL_Route_WallArrow_ElevatorNoiseCue": ["Hotel.Capture.Readability", "Hotel.Capture.TransitionFear", "Hotel.Capture.PatrolDecision"],
    "PATROL_Route_WallArrow_StairAirCue": ["Hotel.Capture.Readability", "Hotel.Capture.TransitionFear", "Hotel.Capture.PatrolDecision"],
    "PATROL_Route_StairDoor_ColdLightLeak": ["Hotel.Capture.Readability", "Hotel.Capture.TransitionFear", "Hotel.Capture.PatrolDecision"],
    "RETURN_Route_FloorColdPatch_AfterRefusal": ["Hotel.Capture.Readability", "Hotel.Capture.ReturnRouteAnomaly"],
    "RETURN_Route_BackKnockDirectionStripe": ["Hotel.Capture.Readability", "Hotel.Capture.ReturnRouteAnomaly"],
    "RETURN_Route_BackKnockDirectionStripe_Return": ["Hotel.Capture.Readability", "Hotel.Capture.ReturnRouteAnomaly"],
    "RETURN_Route_WallStatusSlip_ReportAfterHall": ["Hotel.Capture.Readability", "Hotel.Capture.ReturnRouteAnomaly"],
    "RETURN_Route_WallStatusSlip_Underline": ["Hotel.Capture.Readability", "Hotel.Capture.ReturnRouteAnomaly"],
    "RETURN_Route_FootprintBacktrackA": ["Hotel.Capture.Readability", "Hotel.Capture.ReturnRouteAnomaly"],
    "RETURN_Route_FootprintBacktrackB": ["Hotel.Capture.Readability", "Hotel.Capture.ReturnRouteAnomaly"],
    "RETURN_Route_FootprintBacktrackC": ["Hotel.Capture.Readability", "Hotel.Capture.ReturnRouteAnomaly"],
    "RETURN_Route_CeilingLightmesh_ColdPulseCue": ["Hotel.Capture.Readability", "Hotel.Capture.ReturnRouteAnomaly"],
    "LIGHT_FrontDesk_PhoneCallLampPulse": ["Hotel.Feedback.PhoneRingLamp", "Hotel.Capture.Readability"],
    "LIGHT_Transition_ElevatorCallPanelDread": ["Hotel.Capture.TransitionFear"],
    "LIGHT_Transition_StairExitCold": ["Hotel.Capture.TransitionFear"],
    "LIGHT_Transition_CaptureEvidenceSoftFill": ["Hotel.Capture.Readability", "Hotel.Capture.TransitionFear"],
    "LIGHT_Transition_EvidenceWideFill": ["Hotel.Capture.Readability", "Hotel.Capture.TransitionFear"],
    "LIGHT_PatrolRoute_DecisionCueFloorFill": ["Hotel.Capture.Readability", "Hotel.Capture.PatrolDecision", "Hotel.Feedback.PatrolListenLight"],
    "LIGHT_ReturnRoute_ColdPulseAfterRefusal": ["Hotel.Capture.Readability", "Hotel.Capture.ReturnRouteAnomaly", "Hotel.Feedback.ReturnRouteLight"],
    "LIGHT_GuestHall_CaptureEvidenceDoorFill": ["Hotel.Capture.Readability", "Hotel.Capture.Room203Surface"],
    "LIGHT_GuestHall_Room203AftershockPaperSkimFill": ["Hotel.Capture.Readability", "Hotel.Capture.Room203Aftershock"],
    "LIGHT_MonitorToHall_CaptureEvidenceGreenFill": ["Hotel.Capture.Readability", "Hotel.Capture.PostReportMonitorMismatch", "Hotel.Feedback.PostReportMonitorMismatchLight"],
    "LIGHT_LobbyDoor_PostReportRattleColdPulse": ["Hotel.Capture.Readability", "Hotel.Capture.PostReportDeskWait", "Hotel.Feedback.PostReportDeskWaitLight"],
    "LIGHT_PostReportDeskWait_EvidenceFill": ["Hotel.Capture.Readability", "Hotel.Capture.PostReportDeskWait"],
    "LIGHT_FrontDesk_ReportLog_SelfCorrectionAmberPulse": ["Hotel.Capture.Readability", "Hotel.Capture.PostReportLogSelfCorrection", "Hotel.Feedback.PostReportLogSelfCorrectionLight"],
    "CAPTURE_GuestDoor_15SecondBeatCandidate": ["Hotel.Capture.Room203Surface"],
    "SFX_PhoneRing_FrontDesk_ManualTrigger_v0": ["Hotel.Audio.PhoneRing"],
    "SFX_PhonePickup_FrontDesk_ManualTrigger_v0": ["Hotel.Audio.PhonePickup"],
    "SFX_PhoneLineStatic_FrontDesk_ConnectedCue_v0": ["Hotel.Audio.PhoneLineStatic"],
    "SFX_DoorKnock203_ManualTrigger_v0": ["Hotel.Audio.Room203Knock"],
    "SFX_Room203AftershockRustle_ManualTrigger_v0": ["Hotel.Audio.Room203Aftershock"],
    "SFX_ReportLogFiled_FrontDesk_ManualTrigger_v0": ["Hotel.Audio.ReportLogFiled"],
    "AMB_Elevator_ShaftGroan_Source_v0": ["Hotel.Audio.ElevatorShaftGroan"],
    "AMB_Stairwell_Air_Source_v0": ["Hotel.Audio.StairwellAir"],
    "AMB_PatrolRoute_ElevatorGroanBleed_Source_v0": ["Hotel.Audio.ElevatorShaftGroan", "Hotel.Audio.PatrolDecision"],
    "AMB_PatrolRoute_StairAirBleed_Source_v0": ["Hotel.Audio.StairwellAir", "Hotel.Audio.PatrolDecision"],
    "SFX_PatrolListen_StopLine_ManualTrigger_v0": ["Hotel.Audio.PatrolListen"],
    "SFX_ReturnRoute_BackKnock_ManualTrigger_v0": ["Hotel.Audio.ReturnRoute"],
    "SFX_PostReportMonitorMismatch_ManualTrigger_v0": ["Hotel.Audio.PostReportMonitorMismatch"],
    "SFX_PostReportDeskWait_Rattle_ManualTrigger_v0": ["Hotel.Audio.PostReportDeskWait"],
    "SFX_PostReportLogSelfCorrection_ManualTrigger_v0": ["Hotel.Audio.PostReportLogSelfCorrection"],
}

REQUIRED_AUDIO_LABELS = [
    "SFX_PhoneRing_FrontDesk_ManualTrigger_v0",
    "SFX_PhonePickup_FrontDesk_ManualTrigger_v0",
    "SFX_PhoneLineStatic_FrontDesk_ConnectedCue_v0",
    "SFX_DoorKnock203_ManualTrigger_v0",
    "SFX_Room203AftershockRustle_ManualTrigger_v0",
    "SFX_ReportLogFiled_FrontDesk_ManualTrigger_v0",
    "AMB_Lobby_FluorescentHum_Source_v0",
    "AMB_GuestHall_Drone_Source_v0",
    "AMB_Elevator_ShaftGroan_Source_v0",
    "AMB_Stairwell_Air_Source_v0",
    "AMB_PatrolRoute_ElevatorGroanBleed_Source_v0",
    "AMB_PatrolRoute_StairAirBleed_Source_v0",
    "SFX_PatrolListen_StopLine_ManualTrigger_v0",
    "SFX_ReturnRoute_BackKnock_ManualTrigger_v0",
    "SFX_PostReportMonitorMismatch_ManualTrigger_v0",
    "SFX_PostReportDeskWait_Rattle_ManualTrigger_v0",
    "SFX_PostReportLogSelfCorrection_ManualTrigger_v0",
]

MOVABLE_STATIC_MESH_LABELS = [
    "PROP_FrontDesk_Phone_ReceiverCue",
    "PROP_FrontDesk_Phone_ReceiverLeftCap",
    "PROP_FrontDesk_Phone_ReceiverRightCap",
    "PROP_FrontDesk_Phone_ReceiverLeftRoundCup",
    "PROP_FrontDesk_Phone_ReceiverRightRoundCup",
    "PROP_FrontDesk_Phone_ReceiverAuthoredSilhouette",
    "PROP_FrontDesk_Phone_AuthoredCoiledCord",
    "PROP_GuestHall_RightWall_AuthoredPeelingWallpaper_CameraReadable",
    "PROP_GuestHall_RightWall_AuthoredPeelingWallpaper_Room203",
    "PROP_GuestHall_RightWall_Room203AftershockLoosePaper",
    "PROP_GuestHall_RightWall_Room203AftershockHighCurl",
    "PROP_GuestHall_RightWall_Room203AftershockLowCurl",
    "PROP_GuestHall_Room203_AuthoredPaneledDoor",
    "PROP_GuestHall_Room203_AuthoredHandleLever",
    "PROP_GuestHall_Room203_LatchJoltCue",
    "PROP_GuestHall_Room203_ChainJoltCue",
    "PROP_GuestHall_Room203_AuthoredChainLinks",
    "PROP_GuestHall_Room203_DoorEdgeSlamShadowCue",
    "PROP_GuestHall_Room203_NoticeCornerJoltCue",
    "PROP_GuestHall_Room203_AuthoredTornNotice",
    "PROP_FrontDesk_ReportLog_FiledStampCue",
    "PROP_FrontDesk_ReportLog_SelfCorrectedRoom203OpenLine",
    "PROP_FrontDesk_ReportLog_SelfCorrectedNoGuestLine",
    "PROP_FrontDesk_ReportLog_SelfCorrectedTimestampSlash",
    "PROP_Lobby_GlassDoor_PostReportHandleRattleBar",
    "PROP_Lobby_GlassDoor_PostReportLatchRattlePin",
    "PROP_Lobby_GlassDoor_PostReportTapeLooseEnd",
]

NON_INTERACTIVE_POLISH_LABELS = [
    "PROP_FrontDesk_DeskMat_UnderPhoneAndLog",
    "PROP_FrontDesk_Phone_Keypad_ReadableCue",
    "PROP_FrontDesk_Phone_ButtonRowTop",
    "PROP_FrontDesk_Phone_ButtonRowBottom",
    "PROP_FrontDesk_Phone_CradleLeftHook",
    "PROP_FrontDesk_Phone_CradleRightHook",
    "PROP_FrontDesk_Phone_HookSwitch_DepressedCue",
    "PROP_FrontDesk_Phone_AuthoredCurvedBody",
    "PROP_FrontDesk_Phone_ReceiverAuthoredSilhouette",
    "PROP_FrontDesk_Phone_CoiledCordLoopA",
    "PROP_FrontDesk_Phone_CoiledCordLoopB",
    "PROP_FrontDesk_Phone_CoiledCordLoopC",
    "PROP_FrontDesk_Phone_AuthoredCoiledCord",
    "PROP_FrontDesk_Phone_RoundedDialPlate",
    "PROP_FrontDesk_Phone_DialFingerHoleTop",
    "PROP_FrontDesk_Phone_DialFingerHoleLeft",
    "PROP_FrontDesk_Phone_DialFingerHoleRight",
    "PROP_FrontDesk_Phone_DialFingerStop",
    "PROP_FrontDesk_Phone_ReceiverLeftRoundCup",
    "PROP_FrontDesk_Phone_ReceiverRightRoundCup",
    "PROP_FrontDesk_Phone_CordRoundLoopA",
    "PROP_FrontDesk_Phone_CordRoundLoopB",
    "PROP_FrontDesk_Phone_CordRoundLoopC",
    "PROP_FrontDesk_ServiceBell_Dome",
    "PROP_FrontDesk_ServiceBell_Button",
    "PROP_FrontDesk_DeskLamp_RoundFoot",
    "PROP_FrontDesk_DeskLamp_ThinStem",
    "PROP_FrontDesk_DeskLamp_ShadeCurvedSilhouette",
    "PROP_FrontDesk_CallSlip_Room203_CameraMismatchCue",
    "PROP_FrontDesk_CallSlip_Underline203",
    "PROP_Surveillance_Monitor_PostReportFeedFrame",
    "PROP_Surveillance_Monitor_PostReportStaticBarA",
    "PROP_Surveillance_Monitor_PostReportStaticBarB",
    "PROP_Surveillance_Monitor_PostReportOpenDoorGlyph",
    "PROP_Surveillance_Monitor_PostReportRoom203Dot",
    "PROP_Surveillance_Monitor_PostReportTimestampSmear",
    "PROP_FrontDesk_FloorWaitMarker_PostReport",
    "PROP_FrontDesk_CounterHoldLine_PostReport",
    "PROP_Lobby_GlassDoor_PostReportHoldClosedTape",
    "PROP_Lobby_GlassDoor_PostReportOutsidePalmSmear",
    "PROP_Lobby_GlassDoor_PostReportNoGuestReflection",
    "LIGHTMESH_LobbyDoor_PostReportRattleCue",
    "PROP_FrontDesk_ReportLog_ClipboardClip_Readable",
    "PROP_FrontDesk_ReportLog_IncidentHeaderCue",
    "PROP_FrontDesk_ReportLog_Room203EntryLine",
    "PROP_FrontDesk_ReportLog_TimeBoxCue",
    "PROP_FrontDesk_ReportLog_RefusedCheckbox",
    "PROP_FrontDesk_ReportLog_RefusedCheckmarkShort",
    "PROP_FrontDesk_ReportLog_RefusedCheckmarkLong",
    "PROP_FrontDesk_ReportLog_FiledStampCue",
    "PROP_FrontDesk_ReportLog_PenRest",
    "PROP_FrontDesk_ReportLog_PenTip",
    "PROP_FrontDesk_ReportLog_AuthoredCurledPages",
    "PROP_FrontDesk_ReportLog_BinderRingTop",
    "PROP_FrontDesk_ReportLog_BinderRingBottom",
    "PROP_FrontDesk_ReportLog_RedInkSmear",
    "PROP_FrontDesk_ReportLog_SelfCorrectedRoom203OpenLine",
    "PROP_FrontDesk_ReportLog_SelfCorrectedNoGuestLine",
    "PROP_FrontDesk_ReportLog_SelfCorrectedTimestampSlash",
    "LIGHTMESH_FrontDesk_ReportLog_SelfCorrectionCue",
    "PROP_FrontDesk_BackShelf_KeyHookA",
    "PROP_FrontDesk_BackShelf_KeyHookB",
    "PROP_FrontDesk_BackShelf_KeyHookC",
    "PROP_FrontDesk_BackShelf_KeyTag203",
    "PROP_Lobby_GlassDoor_PostReportHandleRattleBar",
    "PROP_Lobby_GlassDoor_PostReportLatchRattlePin",
    "PROP_Lobby_GlassDoor_PostReportTapeLooseEnd",
    "PROP_GuestHall_RightWall_Baseboard_RunTo203_A",
    "PROP_GuestHall_RightWall_Baseboard_RunTo203_B",
    "PROP_GuestHall_LeftWall_Baseboard_CameraSide",
    "PROP_GuestHall_Room203_FramePaintChip_LeftTop",
    "PROP_GuestHall_Room203_FramePaintChip_LeftLow",
    "PROP_GuestHall_Room203_FramePaintChip_RightMid",
    "PROP_GuestHall_Room203_ThresholdDustCollect",
    "PROP_GuestHall_LeftWall_DampPatch_CameraSide",
    "PROP_GuestHall_RightWall_FadedWallpaperStripe_Room203_A",
    "PROP_GuestHall_RightWall_FadedWallpaperStripe_Room203_B",
    "PROP_GuestHall_RightWall_FadedWallpaperStripe_Room203_C",
    "PROP_GuestHall_RightWall_FadedWallpaperStripe_Room203_D",
    "PROP_GuestHall_RightWall_FadedWallpaperWaterline_Room203",
    "PROP_GuestHall_RightWall_AuthoredDampUnderPeel_Room203Approach",
    "PROP_GuestHall_RightWall_AuthoredPeelingWallpaper_CameraReadable",
    "PROP_GuestHall_RightWall_AuthoredPeelingWallpaper_Room203",
    "PROP_GuestHall_RightWall_Room203AftershockTearShadow",
    "PROP_GuestHall_RightWall_Room203AftershockLoosePaper",
    "PROP_GuestHall_RightWall_Room203AftershockHighCurl",
    "PROP_GuestHall_RightWall_Room203AftershockLowCurl",
    "PROP_GuestHall_RightWall_Room203AftershockRawEdgeThreads",
    "PROP_GuestHall_Floor_AuthoredScuffPath_ToRoom203",
    "PROP_GuestHall_Ceiling_AuthoredWaterStain_FluorescentB",
    "PROP_GuestHall_Room203_AuthoredPaneledDoor",
    "PROP_GuestHall_Room203_HandleBackplate_Readable",
    "PROP_GuestHall_Room203_AuthoredHandleLever",
    "PROP_GuestHall_Room203_LatchJoltCue",
    "PROP_GuestHall_Room203_ChainJoltCue",
    "PROP_GuestHall_Room203_AuthoredChainLinks",
    "PROP_GuestHall_Room203_DoorEdgeSlamShadowCue",
    "PROP_GuestHall_Room203_NoticeCornerJoltCue",
    "PROP_GuestHall_Room203_AuthoredTornNotice",
    "PROP_GuestHall_Room203_PeepholeBlackCue",
    "PROP_GuestHall_Room203_DoNotOpenNotice",
    "PROP_GuestHall_Room203_NoticeUnderline",
    "PROP_GuestHall_Room203_ThresholdShadow",
    "TRANSITION_Elevator_CallPanel_SoundCueAnchor",
    "TRANSITION_Elevator_FloorIndicator_WrongFloorCue",
    "TRANSITION_Elevator_ClosedSeam_ShadowCue",
    "TRANSITION_EmergencyStair_ExitSign_ColdCue",
    "TRANSITION_EmergencyStair_DoorHandle_ShadowCue",
    "TRANSITION_ServiceBackHall_ChainLockedShortcutCue",
    "PATROL_Route_DecisionStopLine_ListenBeforeMoving",
    "PATROL_Route_DecisionStopLine_CenterBreak",
    "PATROL_Route_ElevatorTrack_FootstepA",
    "PATROL_Route_ElevatorTrack_FootstepB",
    "PATROL_Route_ElevatorTrack_FootstepStopped",
    "PATROL_Route_StairReturn_FootstepA",
    "PATROL_Route_StairReturn_FootstepB",
    "PATROL_Route_StairReturn_ScrapeMark",
    "PATROL_Route_DroppedKeyTag_ReturnCue",
    "PATROL_Route_NightAuditClipboard_ElevatorOrStairChoice",
    "PATROL_Route_Clipboard_ElevatorMark",
    "PATROL_Route_Clipboard_StairMark",
    "PATROL_Route_WallArrow_ElevatorNoiseCue",
    "PATROL_Route_WallArrow_StairAirCue",
    "PATROL_Route_StairDoor_ColdLightLeak",
]

REQUIRED_STATIC_MESH_REFERENCES = {
    "PROP_FrontDesk_Phone_AuthoredCurvedBody": "/Game/Hotel/Meshes/SM_FrontDesk_OldPhoneBody_v0.SM_FrontDesk_OldPhoneBody_v0",
    "PROP_FrontDesk_Phone_ReceiverAuthoredSilhouette": "/Game/Hotel/Meshes/SM_FrontDesk_CurvedReceiver_v0.SM_FrontDesk_CurvedReceiver_v0",
    "PROP_FrontDesk_Phone_AuthoredCoiledCord": "/Game/Hotel/Meshes/SM_FrontDesk_CoiledPhoneCord_v0.SM_FrontDesk_CoiledPhoneCord_v0",
    "PROP_FrontDesk_ReportLog_AuthoredCurledPages": "/Game/Hotel/Meshes/SM_FrontDesk_CurledLedgerPages_v0.SM_FrontDesk_CurledLedgerPages_v0",
    "PROP_GuestHall_Room203_AuthoredPaneledDoor": "/Game/Hotel/Meshes/SM_Room203_PaneledDoor_v0.SM_Room203_PaneledDoor_v0",
    "PROP_GuestHall_Room203_AuthoredChainLinks": "/Game/Hotel/Meshes/SM_Room203_ChainLinks_v0.SM_Room203_ChainLinks_v0",
    "PROP_GuestHall_Room203_AuthoredTornNotice": "/Game/Hotel/Meshes/SM_Room203_TornNotice_v0.SM_Room203_TornNotice_v0",
    "PROP_GuestHall_Room203_AuthoredHandleLever": "/Game/Hotel/Meshes/SM_Room203_HandleLever_v0.SM_Room203_HandleLever_v0",
    "PROP_GuestHall_RightWall_AuthoredDampUnderPeel_Room203Approach": "/Game/Hotel/Meshes/SM_GuestHall_PeelingWallpaperPatch_v0.SM_GuestHall_PeelingWallpaperPatch_v0",
    "PROP_GuestHall_RightWall_AuthoredPeelingWallpaper_CameraReadable": "/Game/Hotel/Meshes/SM_GuestHall_PeelingWallpaperPatch_v0.SM_GuestHall_PeelingWallpaperPatch_v0",
    "PROP_GuestHall_RightWall_AuthoredPeelingWallpaper_Room203": "/Game/Hotel/Meshes/SM_GuestHall_PeelingWallpaperPatch_v0.SM_GuestHall_PeelingWallpaperPatch_v0",
    "PROP_GuestHall_RightWall_Room203AftershockTearShadow": "/Game/Hotel/Meshes/SM_GuestHall_Room203AftershockTearShadow_v0.SM_GuestHall_Room203AftershockTearShadow_v0",
    "PROP_GuestHall_RightWall_Room203AftershockLoosePaper": "/Game/Hotel/Meshes/SM_GuestHall_Room203AftershockPaper_v0.SM_GuestHall_Room203AftershockPaper_v0",
    "PROP_GuestHall_RightWall_Room203AftershockHighCurl": "/Game/Hotel/Meshes/SM_GuestHall_Room203AftershockPaper_v0.SM_GuestHall_Room203AftershockPaper_v0",
    "PROP_GuestHall_RightWall_Room203AftershockLowCurl": "/Game/Hotel/Meshes/SM_GuestHall_Room203AftershockPaper_v0.SM_GuestHall_Room203AftershockPaper_v0",
    "PROP_GuestHall_RightWall_Room203AftershockRawEdgeThreads": "/Game/Hotel/Meshes/SM_GuestHall_Room203AftershockRawEdge_v0.SM_GuestHall_Room203AftershockRawEdge_v0",
    "PROP_GuestHall_Floor_AuthoredScuffPath_ToRoom203": "/Game/Hotel/Meshes/SM_GuestHall_FloorScuffCluster_v0.SM_GuestHall_FloorScuffCluster_v0",
    "PROP_GuestHall_Ceiling_AuthoredWaterStain_FluorescentB": "/Game/Hotel/Meshes/SM_GuestHall_CeilingWaterStain_v0.SM_GuestHall_CeilingWaterStain_v0",
}

FORBIDDEN_PUBLIC_ASSET_ROOTS = [
    "/Game/Fab/",
    "/Game/Megascans/",
    "/Game/MSPresets/",
    "/Game/Marketplace/",
    "/Game/AnimationStarterPack/",
    "/Game/GameAnimationSample/",
    "/Game/Lyra/",
    "/Game/Paragon",
    "/Game/InfinityBlade",
    "/Game/MetaHumans/",
]


def fail(message: str) -> None:
    raise RuntimeError(f"[HotelSpineVerify] {message}")


def ensure_public_safe_asset_path(owner: str, asset) -> None:
    if asset is None:
        return
    try:
        asset_path = asset.get_path_name()
    except Exception:
        return
    for forbidden_root in FORBIDDEN_PUBLIC_ASSET_ROOTS:
        if asset_path.startswith(forbidden_root):
            fail(
                f"{owner} references forbidden public-repo asset root {forbidden_root}: {asset_path}. "
                "Use a project-authored asset or record explicit public redistribution rights before product-map use."
            )


for asset_path in REQUIRED_ASSETS:
    if not unreal.EditorAssetLibrary.does_asset_exist(asset_path):
        fail(f"Missing asset: {asset_path}")

unreal.EditorLevelLibrary.load_level(MAP_PATH)
actors_by_label = {actor.get_actor_label(): actor for actor in unreal.EditorLevelLibrary.get_all_level_actors()}
labels = set(actors_by_label)
missing_labels = [label for label in REQUIRED_ACTOR_LABELS if label not in labels]
if missing_labels:
    fail("Missing actors: " + ", ".join(missing_labels))

for label, expected_tags in REQUIRED_ACTOR_TAGS.items():
    actor = actors_by_label.get(label)
    if actor is None:
        fail(f"Missing tagged actor: {label}")
    actual_tags = {str(tag) for tag in actor.tags}
    missing_tags = [tag for tag in expected_tags if tag not in actual_tags]
    if missing_tags:
        fail(f"Actor {label} is missing tags: {', '.join(missing_tags)}")

for label in REQUIRED_AUDIO_LABELS:
    actor = actors_by_label.get(label)
    if actor is None:
        fail(f"Missing audio actor: {label}")
    try:
        audio_component = actor.get_editor_property("audio_component")
    except Exception as exc:
        fail(f"Actor {label} has no audio_component: {exc}")
    if audio_component is None:
        fail(f"Actor {label} has no audio component")
    if not audio_component.get_editor_property("sound"):
        fail(f"Actor {label} has no sound assigned")
    if label.startswith("SFX_") and audio_component.get_editor_property("auto_activate"):
        fail(f"One-shot cue {label} must not auto activate")

for label in MOVABLE_STATIC_MESH_LABELS:
    actor = actors_by_label.get(label)
    component = actor.static_mesh_component if actor is not None and hasattr(actor, "static_mesh_component") else None
    if component is None:
        fail(f"Actor {label} must have a static mesh component")
    if component.get_editor_property("mobility") != unreal.ComponentMobility.MOVABLE:
        fail(f"Actor {label} must be movable for live interaction feedback")

for label in NON_INTERACTIVE_POLISH_LABELS:
    actor = actors_by_label.get(label)
    if actor is None:
        fail(f"Missing non-interactive polish actor: {label}")
    interact_tags = [str(tag) for tag in actor.tags if str(tag).startswith("Hotel.Interact.")]
    if interact_tags:
        fail(f"Polish actor {label} must not carry interaction tags: {', '.join(interact_tags)}")

for label, expected_mesh_path in REQUIRED_STATIC_MESH_REFERENCES.items():
    actor = actors_by_label.get(label)
    component = actor.static_mesh_component if actor is not None and hasattr(actor, "static_mesh_component") else None
    if component is None:
        fail(f"Actor {label} must have a static mesh component")
    mesh = component.get_editor_property("static_mesh")
    if mesh is None:
        fail(f"Actor {label} has no static mesh assigned")
    actual_mesh_path = mesh.get_path_name()
    if actual_mesh_path != expected_mesh_path:
        fail(f"Actor {label} uses {actual_mesh_path}, expected {expected_mesh_path}")

for actor in actors_by_label.values():
    label = actor.get_actor_label()
    if hasattr(actor, "static_mesh_component"):
        component = actor.static_mesh_component
        ensure_public_safe_asset_path(label, component.get_editor_property("static_mesh"))
        try:
            material_count = component.get_num_materials()
        except Exception:
            material_count = 0
        for material_index in range(material_count):
            ensure_public_safe_asset_path(f"{label} material {material_index}", component.get_material(material_index))
    try:
        audio_component = actor.get_editor_property("audio_component")
    except Exception:
        audio_component = None
    if audio_component is not None:
        ensure_public_safe_asset_path(label, audio_component.get_editor_property("sound"))

unreal.log(
    f"[HotelSpineVerify] Verified {len(REQUIRED_ASSETS)} assets, "
    f"{len(REQUIRED_ACTOR_LABELS)} required actors, {len(REQUIRED_ACTOR_TAGS)} tagged actors, "
    f"{len(REQUIRED_AUDIO_LABELS)} audio actors, {len(MOVABLE_STATIC_MESH_LABELS)} movable feedback meshes, "
    f"{len(NON_INTERACTIVE_POLISH_LABELS)} non-interactive polish actors, "
    f"and {len(REQUIRED_STATIC_MESH_REFERENCES)} authored mesh references."
)
